// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_cycles.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAgentCycle = `-- name: CreateAgentCycle :one
INSERT INTO agent_cycles (agent_id, cycle_num, started_at, finished_at, duration_ms, llm_prompt, llm_response, tool_calls, token_usage, fast_path_hit, error)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, agent_id, cycle_num, started_at, finished_at, duration_ms, llm_prompt, llm_response, tool_calls, token_usage, fast_path_hit, error, created_at
`

type CreateAgentCycleParams struct {
	AgentID     uuid.UUID          `json:"agent_id"`
	CycleNum    int64              `json:"cycle_num"`
	StartedAt   time.Time          `json:"started_at"`
	FinishedAt  pgtype.Timestamptz `json:"finished_at"`
	DurationMs  pgtype.Int4        `json:"duration_ms"`
	LlmPrompt   pgtype.Text        `json:"llm_prompt"`
	LlmResponse pgtype.Text        `json:"llm_response"`
	ToolCalls   []byte             `json:"tool_calls"`
	TokenUsage  []byte             `json:"token_usage"`
	FastPathHit bool               `json:"fast_path_hit"`
	Error       pgtype.Text        `json:"error"`
}

func (q *Queries) CreateAgentCycle(ctx context.Context, arg CreateAgentCycleParams) (AgentCycle, error) {
	row := q.db.QueryRow(ctx, createAgentCycle,
		arg.AgentID,
		arg.CycleNum,
		arg.StartedAt,
		arg.FinishedAt,
		arg.DurationMs,
		arg.LlmPrompt,
		arg.LlmResponse,
		arg.ToolCalls,
		arg.TokenUsage,
		arg.FastPathHit,
		arg.Error,
	)
	var i AgentCycle
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.CycleNum,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.LlmPrompt,
		&i.LlmResponse,
		&i.ToolCalls,
		&i.TokenUsage,
		&i.FastPathHit,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const listAgentCycles = `-- name: ListAgentCycles :many
SELECT id, agent_id, cycle_num, started_at, finished_at, duration_ms, llm_prompt, llm_response, tool_calls, token_usage, fast_path_hit, error, created_at FROM agent_cycles WHERE agent_id = $1
ORDER BY cycle_num DESC
LIMIT $2
`

type ListAgentCyclesParams struct {
	AgentID uuid.UUID `json:"agent_id"`
	Limit   int32     `json:"limit"`
}

func (q *Queries) ListAgentCycles(ctx context.Context, arg ListAgentCyclesParams) ([]AgentCycle, error) {
	rows, err := q.db.Query(ctx, listAgentCycles, arg.AgentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentCycle{}
	for rows.Next() {
		var i AgentCycle
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.CycleNum,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.LlmPrompt,
			&i.LlmResponse,
			&i.ToolCalls,
			&i.TokenUsage,
			&i.FastPathHit,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
