// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agents.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (user_id, name, strategy_prompt, pair, interval_sec, status, risk_params, llm_params)
VALUES ($1, $2, $3, $4, $5, 'created', $6, $7)
RETURNING id, user_id, name, strategy_prompt, pair, interval_sec, status, risk_params, llm_params, state, aum, investor_count, total_pnl, trade_count, created_at, updated_at
`

type CreateAgentParams struct {
	UserID         uuid.UUID       `json:"user_id"`
	Name           string          `json:"name"`
	StrategyPrompt string          `json:"strategy_prompt"`
	Pair           string          `json:"pair"`
	IntervalSec    int32           `json:"interval_sec"`
	RiskParams     json.RawMessage `json:"risk_params"`
	LlmParams      json.RawMessage `json:"llm_params"`
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, createAgent,
		arg.UserID,
		arg.Name,
		arg.StrategyPrompt,
		arg.Pair,
		arg.IntervalSec,
		arg.RiskParams,
		arg.LlmParams,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.StrategyPrompt,
		&i.Pair,
		&i.IntervalSec,
		&i.Status,
		&i.RiskParams,
		&i.LlmParams,
		&i.State,
		&i.Aum,
		&i.InvestorCount,
		&i.TotalPnl,
		&i.TradeCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAgent = `-- name: DeleteAgent :exec
DELETE FROM agents WHERE id = $1
`

func (q *Queries) DeleteAgent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAgent, id)
	return err
}

const getAgent = `-- name: GetAgent :one
SELECT id, user_id, name, strategy_prompt, pair, interval_sec, status, risk_params, llm_params, state, aum, investor_count, total_pnl, trade_count, created_at, updated_at FROM agents WHERE id = $1
`

func (q *Queries) GetAgent(ctx context.Context, id uuid.UUID) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgent, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.StrategyPrompt,
		&i.Pair,
		&i.IntervalSec,
		&i.Status,
		&i.RiskParams,
		&i.LlmParams,
		&i.State,
		&i.Aum,
		&i.InvestorCount,
		&i.TotalPnl,
		&i.TradeCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgentsByUser = `-- name: ListAgentsByUser :many
SELECT id, user_id, name, strategy_prompt, pair, interval_sec, status, risk_params, llm_params, state, aum, investor_count, total_pnl, trade_count, created_at, updated_at FROM agents
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListAgentsByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
}

func (q *Queries) ListAgentsByUser(ctx context.Context, arg ListAgentsByUserParams) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listAgentsByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.StrategyPrompt,
			&i.Pair,
			&i.IntervalSec,
			&i.Status,
			&i.RiskParams,
			&i.LlmParams,
			&i.State,
			&i.Aum,
			&i.InvestorCount,
			&i.TotalPnl,
			&i.TradeCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentsByUserCursor = `-- name: ListAgentsByUserCursor :many
SELECT id, user_id, name, strategy_prompt, pair, interval_sec, status, risk_params, llm_params, state, aum, investor_count, total_pnl, trade_count, created_at, updated_at FROM agents
WHERE user_id = $1 AND created_at < $2
ORDER BY created_at DESC
LIMIT $3
`

type ListAgentsByUserCursorParams struct {
	UserID    uuid.UUID `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) ListAgentsByUserCursor(ctx context.Context, arg ListAgentsByUserCursorParams) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listAgentsByUserCursor, arg.UserID, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.StrategyPrompt,
			&i.Pair,
			&i.IntervalSec,
			&i.Status,
			&i.RiskParams,
			&i.LlmParams,
			&i.State,
			&i.Aum,
			&i.InvestorCount,
			&i.TotalPnl,
			&i.TradeCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunningAgents = `-- name: ListRunningAgents :many
SELECT id, user_id, name, strategy_prompt, pair, interval_sec, status, risk_params, llm_params, state, aum, investor_count, total_pnl, trade_count, created_at, updated_at FROM agents WHERE status = 'running'
`

func (q *Queries) ListRunningAgents(ctx context.Context) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listRunningAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.StrategyPrompt,
			&i.Pair,
			&i.IntervalSec,
			&i.Status,
			&i.RiskParams,
			&i.LlmParams,
			&i.State,
			&i.Aum,
			&i.InvestorCount,
			&i.TotalPnl,
			&i.TradeCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgent = `-- name: UpdateAgent :one
UPDATE agents
SET name = $2,
    strategy_prompt = $3,
    pair = $4,
    interval_sec = $5,
    risk_params = $6,
    llm_params = $7,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, name, strategy_prompt, pair, interval_sec, status, risk_params, llm_params, state, aum, investor_count, total_pnl, trade_count, created_at, updated_at
`

type UpdateAgentParams struct {
	ID             uuid.UUID       `json:"id"`
	Name           string          `json:"name"`
	StrategyPrompt string          `json:"strategy_prompt"`
	Pair           string          `json:"pair"`
	IntervalSec    int32           `json:"interval_sec"`
	RiskParams     json.RawMessage `json:"risk_params"`
	LlmParams      json.RawMessage `json:"llm_params"`
}

func (q *Queries) UpdateAgent(ctx context.Context, arg UpdateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, updateAgent,
		arg.ID,
		arg.Name,
		arg.StrategyPrompt,
		arg.Pair,
		arg.IntervalSec,
		arg.RiskParams,
		arg.LlmParams,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.StrategyPrompt,
		&i.Pair,
		&i.IntervalSec,
		&i.Status,
		&i.RiskParams,
		&i.LlmParams,
		&i.State,
		&i.Aum,
		&i.InvestorCount,
		&i.TotalPnl,
		&i.TradeCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAgentAUM = `-- name: UpdateAgentAUM :exec
UPDATE agents
SET aum = $2,
    investor_count = $3,
    updated_at = NOW()
WHERE id = $1
`

type UpdateAgentAUMParams struct {
	ID            uuid.UUID `json:"id"`
	Aum           int64     `json:"aum"`
	InvestorCount int32     `json:"investor_count"`
}

func (q *Queries) UpdateAgentAUM(ctx context.Context, arg UpdateAgentAUMParams) error {
	_, err := q.db.Exec(ctx, updateAgentAUM, arg.ID, arg.Aum, arg.InvestorCount)
	return err
}

const updateAgentState = `-- name: UpdateAgentState :exec
UPDATE agents
SET state = $2,
    total_pnl = $3,
    trade_count = $4,
    updated_at = NOW()
WHERE id = $1
`

type UpdateAgentStateParams struct {
	ID         uuid.UUID       `json:"id"`
	State      json.RawMessage `json:"state"`
	TotalPnl   int64           `json:"total_pnl"`
	TradeCount int32           `json:"trade_count"`
}

func (q *Queries) UpdateAgentState(ctx context.Context, arg UpdateAgentStateParams) error {
	_, err := q.db.Exec(ctx, updateAgentState,
		arg.ID,
		arg.State,
		arg.TotalPnl,
		arg.TradeCount,
	)
	return err
}

const updateAgentStatus = `-- name: UpdateAgentStatus :one
UPDATE agents SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, name, strategy_prompt, pair, interval_sec, status, risk_params, llm_params, state, aum, investor_count, total_pnl, trade_count, created_at, updated_at
`

type UpdateAgentStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateAgentStatus(ctx context.Context, arg UpdateAgentStatusParams) (Agent, error) {
	row := q.db.QueryRow(ctx, updateAgentStatus, arg.ID, arg.Status)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.StrategyPrompt,
		&i.Pair,
		&i.IntervalSec,
		&i.Status,
		&i.RiskParams,
		&i.LlmParams,
		&i.State,
		&i.Aum,
		&i.InvestorCount,
		&i.TotalPnl,
		&i.TradeCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
