// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: investments.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createInvestment = `-- name: CreateInvestment :one
INSERT INTO investments (user_id, agent_id, amount, share_ratio)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, agent_id, amount, share_ratio, status, created_at, redeemed_at
`

type CreateInvestmentParams struct {
	UserID     uuid.UUID      `json:"user_id"`
	AgentID    uuid.UUID      `json:"agent_id"`
	Amount     int64          `json:"amount"`
	ShareRatio pgtype.Numeric `json:"share_ratio"`
}

func (q *Queries) CreateInvestment(ctx context.Context, arg CreateInvestmentParams) (Investment, error) {
	row := q.db.QueryRow(ctx, createInvestment,
		arg.UserID,
		arg.AgentID,
		arg.Amount,
		arg.ShareRatio,
	)
	var i Investment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AgentID,
		&i.Amount,
		&i.ShareRatio,
		&i.Status,
		&i.CreatedAt,
		&i.RedeemedAt,
	)
	return i, err
}

const getInvestment = `-- name: GetInvestment :one
SELECT id, user_id, agent_id, amount, share_ratio, status, created_at, redeemed_at FROM investments WHERE id = $1
`

func (q *Queries) GetInvestment(ctx context.Context, id uuid.UUID) (Investment, error) {
	row := q.db.QueryRow(ctx, getInvestment, id)
	var i Investment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AgentID,
		&i.Amount,
		&i.ShareRatio,
		&i.Status,
		&i.CreatedAt,
		&i.RedeemedAt,
	)
	return i, err
}

const listInvestmentsByAgent = `-- name: ListInvestmentsByAgent :many
SELECT id, user_id, agent_id, amount, share_ratio, status, created_at, redeemed_at FROM investments WHERE agent_id = $1 AND status = 'active'
`

func (q *Queries) ListInvestmentsByAgent(ctx context.Context, agentID uuid.UUID) ([]Investment, error) {
	rows, err := q.db.Query(ctx, listInvestmentsByAgent, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Investment{}
	for rows.Next() {
		var i Investment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AgentID,
			&i.Amount,
			&i.ShareRatio,
			&i.Status,
			&i.CreatedAt,
			&i.RedeemedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvestmentsByUser = `-- name: ListInvestmentsByUser :many
SELECT id, user_id, agent_id, amount, share_ratio, status, created_at, redeemed_at FROM investments WHERE user_id = $1 AND status = 'active'
ORDER BY created_at DESC
`

func (q *Queries) ListInvestmentsByUser(ctx context.Context, userID uuid.UUID) ([]Investment, error) {
	rows, err := q.db.Query(ctx, listInvestmentsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Investment{}
	for rows.Next() {
		var i Investment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AgentID,
			&i.Amount,
			&i.ShareRatio,
			&i.Status,
			&i.CreatedAt,
			&i.RedeemedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const redeemInvestment = `-- name: RedeemInvestment :one
UPDATE investments SET status = 'redeemed', redeemed_at = NOW()
WHERE id = $1
RETURNING id, user_id, agent_id, amount, share_ratio, status, created_at, redeemed_at
`

func (q *Queries) RedeemInvestment(ctx context.Context, id uuid.UUID) (Investment, error) {
	row := q.db.QueryRow(ctx, redeemInvestment, id)
	var i Investment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AgentID,
		&i.Amount,
		&i.ShareRatio,
		&i.Status,
		&i.CreatedAt,
		&i.RedeemedAt,
	)
	return i, err
}
