// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ledger.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createLedgerEntry = `-- name: CreateLedgerEntry :one
INSERT INTO ledger_entries (user_id, agent_id, type, amount, balance)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, agent_id, type, amount, balance, created_at
`

type CreateLedgerEntryParams struct {
	UserID  uuid.UUID `json:"user_id"`
	AgentID uuid.UUID `json:"agent_id"`
	Type    string    `json:"type"`
	Amount  int64     `json:"amount"`
	Balance int64     `json:"balance"`
}

func (q *Queries) CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) (LedgerEntry, error) {
	row := q.db.QueryRow(ctx, createLedgerEntry,
		arg.UserID,
		arg.AgentID,
		arg.Type,
		arg.Amount,
		arg.Balance,
	)
	var i LedgerEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AgentID,
		&i.Type,
		&i.Amount,
		&i.Balance,
		&i.CreatedAt,
	)
	return i, err
}

const listLedgerByUser = `-- name: ListLedgerByUser :many
SELECT id, user_id, agent_id, type, amount, balance, created_at FROM ledger_entries WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListLedgerByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
}

func (q *Queries) ListLedgerByUser(ctx context.Context, arg ListLedgerByUserParams) ([]LedgerEntry, error) {
	rows, err := q.db.Query(ctx, listLedgerByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerEntry{}
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AgentID,
			&i.Type,
			&i.Amount,
			&i.Balance,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerByUserAndAgent = `-- name: ListLedgerByUserAndAgent :many
SELECT id, user_id, agent_id, type, amount, balance, created_at FROM ledger_entries
WHERE user_id = $1 AND agent_id = $2
ORDER BY created_at DESC
`

type ListLedgerByUserAndAgentParams struct {
	UserID  uuid.UUID `json:"user_id"`
	AgentID uuid.UUID `json:"agent_id"`
}

func (q *Queries) ListLedgerByUserAndAgent(ctx context.Context, arg ListLedgerByUserAndAgentParams) ([]LedgerEntry, error) {
	rows, err := q.db.Query(ctx, listLedgerByUserAndAgent, arg.UserID, arg.AgentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerEntry{}
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AgentID,
			&i.Type,
			&i.Amount,
			&i.Balance,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
