// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mcp_servers.sql

package store

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const bindAgentMCP = `-- name: BindAgentMCP :exec
INSERT INTO agent_mcp_bindings (agent_id, server_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type BindAgentMCPParams struct {
	AgentID  uuid.UUID `json:"agent_id"`
	ServerID uuid.UUID `json:"server_id"`
}

func (q *Queries) BindAgentMCP(ctx context.Context, arg BindAgentMCPParams) error {
	_, err := q.db.Exec(ctx, bindAgentMCP, arg.AgentID, arg.ServerID)
	return err
}

const createMCPServer = `-- name: CreateMCPServer :one
INSERT INTO mcp_servers (name, url, type, tools, is_public, owner_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, url, type, tools, is_public, owner_id, status, created_at
`

type CreateMCPServerParams struct {
	Name     string          `json:"name"`
	Url      string          `json:"url"`
	Type     string          `json:"type"`
	Tools    json.RawMessage `json:"tools"`
	IsPublic bool            `json:"is_public"`
	OwnerID  pgtype.UUID     `json:"owner_id"`
}

func (q *Queries) CreateMCPServer(ctx context.Context, arg CreateMCPServerParams) (McpServer, error) {
	row := q.db.QueryRow(ctx, createMCPServer,
		arg.Name,
		arg.Url,
		arg.Type,
		arg.Tools,
		arg.IsPublic,
		arg.OwnerID,
	)
	var i McpServer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Type,
		&i.Tools,
		&i.IsPublic,
		&i.OwnerID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getMCPServer = `-- name: GetMCPServer :one
SELECT id, name, url, type, tools, is_public, owner_id, status, created_at FROM mcp_servers WHERE id = $1
`

func (q *Queries) GetMCPServer(ctx context.Context, id uuid.UUID) (McpServer, error) {
	row := q.db.QueryRow(ctx, getMCPServer, id)
	var i McpServer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Type,
		&i.Tools,
		&i.IsPublic,
		&i.OwnerID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listAgentMCPServers = `-- name: ListAgentMCPServers :many
SELECT ms.id, ms.name, ms.url, ms.type, ms.tools, ms.is_public, ms.owner_id, ms.status, ms.created_at FROM mcp_servers ms
JOIN agent_mcp_bindings amb ON ms.id = amb.server_id
WHERE amb.agent_id = $1
`

func (q *Queries) ListAgentMCPServers(ctx context.Context, agentID uuid.UUID) ([]McpServer, error) {
	rows, err := q.db.Query(ctx, listAgentMCPServers, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []McpServer{}
	for rows.Next() {
		var i McpServer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Type,
			&i.Tools,
			&i.IsPublic,
			&i.OwnerID,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMCPServersByOwner = `-- name: ListMCPServersByOwner :many
SELECT id, name, url, type, tools, is_public, owner_id, status, created_at FROM mcp_servers WHERE owner_id = $1 AND status = 'active'
`

func (q *Queries) ListMCPServersByOwner(ctx context.Context, ownerID pgtype.UUID) ([]McpServer, error) {
	rows, err := q.db.Query(ctx, listMCPServersByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []McpServer{}
	for rows.Next() {
		var i McpServer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Type,
			&i.Tools,
			&i.IsPublic,
			&i.OwnerID,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicMCPServers = `-- name: ListPublicMCPServers :many
SELECT id, name, url, type, tools, is_public, owner_id, status, created_at FROM mcp_servers WHERE is_public = true AND status = 'active'
`

func (q *Queries) ListPublicMCPServers(ctx context.Context) ([]McpServer, error) {
	rows, err := q.db.Query(ctx, listPublicMCPServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []McpServer{}
	for rows.Next() {
		var i McpServer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Type,
			&i.Tools,
			&i.IsPublic,
			&i.OwnerID,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unbindAgentMCP = `-- name: UnbindAgentMCP :exec
DELETE FROM agent_mcp_bindings WHERE agent_id = $1 AND server_id = $2
`

type UnbindAgentMCPParams struct {
	AgentID  uuid.UUID `json:"agent_id"`
	ServerID uuid.UUID `json:"server_id"`
}

func (q *Queries) UnbindAgentMCP(ctx context.Context, arg UnbindAgentMCPParams) error {
	_, err := q.db.Exec(ctx, unbindAgentMCP, arg.AgentID, arg.ServerID)
	return err
}

const updateMCPServerStatus = `-- name: UpdateMCPServerStatus :exec
UPDATE mcp_servers SET status = $2 WHERE id = $1
`

type UpdateMCPServerStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateMCPServerStatus(ctx context.Context, arg UpdateMCPServerStatusParams) error {
	_, err := q.db.Exec(ctx, updateMCPServerStatus, arg.ID, arg.Status)
	return err
}
