// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	ID             uuid.UUID       `json:"id"`
	UserID         uuid.UUID       `json:"user_id"`
	Name           string          `json:"name"`
	StrategyPrompt string          `json:"strategy_prompt"`
	Pair           string          `json:"pair"`
	IntervalSec    int32           `json:"interval_sec"`
	Status         string          `json:"status"`
	RiskParams     json.RawMessage `json:"risk_params"`
	LlmParams      json.RawMessage `json:"llm_params"`
	State          json.RawMessage `json:"state"`
	Aum            int64           `json:"aum"`
	InvestorCount  int32           `json:"investor_count"`
	TotalPnl       int64           `json:"total_pnl"`
	TradeCount     int32           `json:"trade_count"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
}

type AgentCycle struct {
	ID          uuid.UUID          `json:"id"`
	AgentID     uuid.UUID          `json:"agent_id"`
	CycleNum    int64              `json:"cycle_num"`
	StartedAt   time.Time          `json:"started_at"`
	FinishedAt  pgtype.Timestamptz `json:"finished_at"`
	DurationMs  pgtype.Int4        `json:"duration_ms"`
	LlmPrompt   pgtype.Text        `json:"llm_prompt"`
	LlmResponse pgtype.Text        `json:"llm_response"`
	ToolCalls   []byte             `json:"tool_calls"`
	TokenUsage  []byte             `json:"token_usage"`
	FastPathHit bool               `json:"fast_path_hit"`
	Error       pgtype.Text        `json:"error"`
	CreatedAt   time.Time          `json:"created_at"`
}

type AgentMcpBinding struct {
	AgentID  uuid.UUID `json:"agent_id"`
	ServerID uuid.UUID `json:"server_id"`
}

type Investment struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	AgentID    uuid.UUID          `json:"agent_id"`
	Amount     int64              `json:"amount"`
	ShareRatio pgtype.Numeric     `json:"share_ratio"`
	Status     string             `json:"status"`
	CreatedAt  time.Time          `json:"created_at"`
	RedeemedAt pgtype.Timestamptz `json:"redeemed_at"`
}

type LedgerEntry struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	AgentID   uuid.UUID `json:"agent_id"`
	Type      string    `json:"type"`
	Amount    int64     `json:"amount"`
	Balance   int64     `json:"balance"`
	CreatedAt time.Time `json:"created_at"`
}

type McpServer struct {
	ID        uuid.UUID       `json:"id"`
	Name      string          `json:"name"`
	Url       string          `json:"url"`
	Type      string          `json:"type"`
	Tools     json.RawMessage `json:"tools"`
	IsPublic  bool            `json:"is_public"`
	OwnerID   pgtype.UUID     `json:"owner_id"`
	Status    string          `json:"status"`
	CreatedAt time.Time       `json:"created_at"`
}

type RiskEvent struct {
	ID        uuid.UUID       `json:"id"`
	AgentID   uuid.UUID       `json:"agent_id"`
	EventType string          `json:"event_type"`
	Details   json.RawMessage `json:"details"`
	CreatedAt time.Time       `json:"created_at"`
}

type TradeLog struct {
	ID           uuid.UUID   `json:"id"`
	AgentID      uuid.UUID   `json:"agent_id"`
	CycleNum     int64       `json:"cycle_num"`
	Action       string      `json:"action"`
	Pair         string      `json:"pair"`
	Amount       int64       `json:"amount"`
	Price        int64       `json:"price"`
	Pnl          int64       `json:"pnl"`
	RiskApproved bool        `json:"risk_approved"`
	RiskReason   pgtype.Text `json:"risk_reason"`
	CreatedAt    time.Time   `json:"created_at"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	Address   string    `json:"address"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
