// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: risk_events.sql

package store

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createRiskEvent = `-- name: CreateRiskEvent :one
INSERT INTO risk_events (agent_id, event_type, details)
VALUES ($1, $2, $3)
RETURNING id, agent_id, event_type, details, created_at
`

type CreateRiskEventParams struct {
	AgentID   uuid.UUID       `json:"agent_id"`
	EventType string          `json:"event_type"`
	Details   json.RawMessage `json:"details"`
}

func (q *Queries) CreateRiskEvent(ctx context.Context, arg CreateRiskEventParams) (RiskEvent, error) {
	row := q.db.QueryRow(ctx, createRiskEvent, arg.AgentID, arg.EventType, arg.Details)
	var i RiskEvent
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.EventType,
		&i.Details,
		&i.CreatedAt,
	)
	return i, err
}

const listRiskEventsByAgent = `-- name: ListRiskEventsByAgent :many
SELECT id, agent_id, event_type, details, created_at FROM risk_events WHERE agent_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListRiskEventsByAgentParams struct {
	AgentID uuid.UUID `json:"agent_id"`
	Limit   int32     `json:"limit"`
}

func (q *Queries) ListRiskEventsByAgent(ctx context.Context, arg ListRiskEventsByAgentParams) ([]RiskEvent, error) {
	rows, err := q.db.Query(ctx, listRiskEventsByAgent, arg.AgentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RiskEvent{}
	for rows.Next() {
		var i RiskEvent
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.EventType,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
