// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trade_logs.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTradeLog = `-- name: CreateTradeLog :one
INSERT INTO trade_logs (agent_id, cycle_num, action, pair, amount, price, pnl, risk_approved, risk_reason)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, agent_id, cycle_num, action, pair, amount, price, pnl, risk_approved, risk_reason, created_at
`

type CreateTradeLogParams struct {
	AgentID      uuid.UUID   `json:"agent_id"`
	CycleNum     int64       `json:"cycle_num"`
	Action       string      `json:"action"`
	Pair         string      `json:"pair"`
	Amount       int64       `json:"amount"`
	Price        int64       `json:"price"`
	Pnl          int64       `json:"pnl"`
	RiskApproved bool        `json:"risk_approved"`
	RiskReason   pgtype.Text `json:"risk_reason"`
}

func (q *Queries) CreateTradeLog(ctx context.Context, arg CreateTradeLogParams) (TradeLog, error) {
	row := q.db.QueryRow(ctx, createTradeLog,
		arg.AgentID,
		arg.CycleNum,
		arg.Action,
		arg.Pair,
		arg.Amount,
		arg.Price,
		arg.Pnl,
		arg.RiskApproved,
		arg.RiskReason,
	)
	var i TradeLog
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.CycleNum,
		&i.Action,
		&i.Pair,
		&i.Amount,
		&i.Price,
		&i.Pnl,
		&i.RiskApproved,
		&i.RiskReason,
		&i.CreatedAt,
	)
	return i, err
}

const listTradeLogsByAgent = `-- name: ListTradeLogsByAgent :many
SELECT id, agent_id, cycle_num, action, pair, amount, price, pnl, risk_approved, risk_reason, created_at FROM trade_logs WHERE agent_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListTradeLogsByAgentParams struct {
	AgentID uuid.UUID `json:"agent_id"`
	Limit   int32     `json:"limit"`
}

func (q *Queries) ListTradeLogsByAgent(ctx context.Context, arg ListTradeLogsByAgentParams) ([]TradeLog, error) {
	rows, err := q.db.Query(ctx, listTradeLogsByAgent, arg.AgentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TradeLog{}
	for rows.Next() {
		var i TradeLog
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.CycleNum,
			&i.Action,
			&i.Pair,
			&i.Amount,
			&i.Price,
			&i.Pnl,
			&i.RiskApproved,
			&i.RiskReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
