// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (address)
VALUES ($1)
ON CONFLICT (address) DO UPDATE SET updated_at = NOW()
RETURNING id, address, created_at, updated_at
`

func (q *Queries) CreateUser(ctx context.Context, address string) (User, error) {
	row := q.db.QueryRow(ctx, createUser, address)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByAddress = `-- name: GetUserByAddress :one
SELECT id, address, created_at, updated_at FROM users WHERE address = $1
`

func (q *Queries) GetUserByAddress(ctx context.Context, address string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByAddress, address)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, address, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
